### ISSUE TITLE
Unable to click on "Search" icon on Edureka home page using automation script

### ISSUE THREAD

**Issue by inyabss** [tabhresh/Edureka_15thSept#1]
Enter "selenium" in search box and use .click(). Not working
Instead .submit() works perfectly fine
Attaching the script. Please review and provide comments

[edurekaDemo.zip](https://github.com/tabhresh/Edureka_15thSept/files/2408743/edurekaDemo.zip)

**Comment by tabhresh** [comment]
its perfectly fine to use submit in cases where search button is not working... both are correct some places those functionality doesn't work so we use submit which is noting different then Enter Button operation on your keyboard.
