### ISSUE TITLE
Unable to locate Web Element(POM)

### ISSUE THREAD

**Issue by swatigwl01** [tabhresh/Edureka_15thSept#3]
I was trying to practice Page Object Model.I made object repositery and Main java class.when i run main class i got exception"NoSuchElementException ".I understand when this 
exception come so I tried to use Implicit and explicit wait .but
when I tried this wait command I got Nullexception.may be I was using wait command in wrong place.so let me know
how to use wait in Page object model.and resolve this problem.and give example.
/*this is Object Repositry*/
package module8.pom;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;

public class GoogleHomePageObjects {
	

	//public WebDriver driver;
	public GoogleHomePageObjects(WebDriver driver)
	{
		PageFactory.initElements(driver, this);
	}
@FindBy(name="q")
public WebElement txtSearch;

@FindBy(name="btnK")
public WebElement btnSearch;

@FindBy(partialLinkText="Web Browser Automation ")
public WebElement linkSel;

public void SearchGoogle() throws InterruptedException {
	txtSearch.sendKeys("SeleniumHQ");
	btnSearch.submit();
	Thread.sleep(5000);
}

public void ClickSelenium() {
	//driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
    linkSel.click();
}
}

/*this is Main java class*/
package module8.pom;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import java.util.concurrent.TimeUnit;
public class GooglelSearchText {
    public static  WebDriver driver;
	public static void main(String[] args) throws InterruptedException {
		System.setProperty("webdriver.chrome.driver","C:\\Users\\swati\\Selenium\\Installation_stuff\\EXEFiles\\chromedriver.exe");
		
		//driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
		 driver=new ChromeDriver();
		 driver.get("https://www.google.com/");
		 GoogleHomePageObjects page =new  GoogleHomePageObjects(driver
``

**Comment by tabhresh** [comment]
Is this issue still pending?
